import type { Product, Order, KPIData, ChartDataPoint } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    name: "Wireless Noise-Cancelling Headphones",
    sku: "WNC-H001",
    category: "Electronics",
    price: 249.99,
    stock: 142,
    lowStockThreshold: 20,
    status: "in-stock",
    supplier: "TechSound Inc.",
    lastUpdated: "2026-06-20",
  },
  {
    id: "p2",
    name: "Mechanical Gaming Keyboard",
    sku: "MGK-K002",
    category: "Electronics",
    price: 129.99,
    stock: 8,
    lowStockThreshold: 15,
    status: "low-stock",
    supplier: "KeyCraft Co.",
    lastUpdated: "2026-06-22",
  },
  {
    id: "p3",
    name: "Organic Cotton T-Shirt",
    sku: "OCT-A003",
    category: "Apparel",
    price: 34.99,
    stock: 0,
    lowStockThreshold: 30,
    status: "out-of-stock",
    supplier: "EcoWear Ltd.",
    lastUpdated: "2026-06-18",
  },
  {
    id: "p4",
    name: "Premium Yoga Mat",
    sku: "PYM-S004",
    category: "Sports",
    price: 79.99,
    stock: 65,
    lowStockThreshold: 10,
    status: "in-stock",
    supplier: "FitLife Supplies",
    lastUpdated: "2026-06-21",
  },
  {
    id: "p5",
    name: "Cold Brew Coffee Maker",
    sku: "CBM-F005",
    category: "Food & Beverage",
    price: 59.99,
    stock: 12,
    lowStockThreshold: 15,
    status: "low-stock",
    supplier: "BrewMaster Co.",
    lastUpdated: "2026-06-23",
  },
  {
    id: "p6",
    name: "Smart LED Desk Lamp",
    sku: "SLD-H006",
    category: "Home & Garden",
    price: 89.99,
    stock: 234,
    lowStockThreshold: 25,
    status: "in-stock",
    supplier: "LuminaTech",
    lastUpdated: "2026-06-19",
  },
  {
    id: "p7",
    name: "Vitamin D3 Supplements",
    sku: "VD3-HB007",
    category: "Health & Beauty",
    price: 24.99,
    stock: 5,
    lowStockThreshold: 20,
    status: "low-stock",
    supplier: "NutriPlus Corp.",
    lastUpdated: "2026-06-24",
  },
  {
    id: "p8",
    name: "4K Webcam Pro",
    sku: "WCP-E008",
    category: "Electronics",
    price: 199.99,
    stock: 89,
    lowStockThreshold: 10,
    status: "in-stock",
    supplier: "VisionTech",
    lastUpdated: "2026-06-20",
  },
  {
    id: "p9",
    name: "Running Shoes - Ultra Boost",
    sku: "RSU-S009",
    category: "Sports",
    price: 159.99,
    stock: 43,
    lowStockThreshold: 20,
    status: "in-stock",
    supplier: "StridePro",
    lastUpdated: "2026-06-22",
  },
  {
    id: "p10",
    name: "Stainless Steel Water Bottle",
    sku: "SSW-HG010",
    category: "Home & Garden",
    price: 39.99,
    stock: 0,
    lowStockThreshold: 40,
    status: "out-of-stock",
    supplier: "EcoVessel",
    lastUpdated: "2026-06-17",
  },
  {
    id: "p11",
    name: "Car Phone Mount - Magnetic",
    sku: "CPM-A011",
    category: "Automotive",
    price: 29.99,
    stock: 310,
    lowStockThreshold: 50,
    status: "in-stock",
    supplier: "AutoGear Ltd.",
    lastUpdated: "2026-06-23",
  },
  {
    id: "p12",
    name: "JavaScript: The Good Parts",
    sku: "JSG-B012",
    category: "Books",
    price: 44.99,
    stock: 77,
    lowStockThreshold: 10,
    status: "in-stock",
    supplier: "O'Reilly Media",
    lastUpdated: "2026-06-15",
  },
];

export const orders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-2026-0891",
    customer: "Alice Johnson",
    email: "alice@example.com",
    products: [
      { productId: "p1", name: "Wireless Headphones", qty: 1, price: 249.99 },
      { productId: "p6", name: "Smart LED Desk Lamp", qty: 2, price: 89.99 },
    ],
    total: 429.97,
    status: "delivered",
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
  {
    id: "o2",
    orderNumber: "ORD-2026-0892",
    customer: "Bob Martinez",
    email: "bob@example.com",
    products: [{ productId: "p2", name: "Mechanical Keyboard", qty: 1, price: 129.99 }],
    total: 129.99,
    status: "shipped",
    createdAt: "2026-06-20",
    updatedAt: "2026-06-22",
  },
  {
    id: "o3",
    orderNumber: "ORD-2026-0893",
    customer: "Clara Smith",
    email: "clara@example.com",
    products: [{ productId: "p4", name: "Premium Yoga Mat", qty: 2, price: 79.99 }],
    total: 159.98,
    status: "processing",
    createdAt: "2026-06-23",
    updatedAt: "2026-06-23",
  },
  {
    id: "o4",
    orderNumber: "ORD-2026-0894",
    customer: "David Lee",
    email: "david@example.com",
    products: [
      { productId: "p8", name: "4K Webcam Pro", qty: 1, price: 199.99 },
      { productId: "p12", name: "JavaScript Book", qty: 1, price: 44.99 },
    ],
    total: 244.98,
    status: "pending",
    createdAt: "2026-06-24",
    updatedAt: "2026-06-24",
  },
  {
    id: "o5",
    orderNumber: "ORD-2026-0895",
    customer: "Emma Wilson",
    email: "emma@example.com",
    products: [{ productId: "p9", name: "Running Shoes", qty: 1, price: 159.99 }],
    total: 159.99,
    status: "pending",
    createdAt: "2026-06-24",
    updatedAt: "2026-06-24",
  },
  {
    id: "o6",
    orderNumber: "ORD-2026-0890",
    customer: "Frank Chen",
    email: "frank@example.com",
    products: [{ productId: "p5", name: "Cold Brew Coffee Maker", qty: 3, price: 59.99 }],
    total: 179.97,
    status: "cancelled",
    createdAt: "2026-06-14",
    updatedAt: "2026-06-16",
  },
];

export const kpiData: KPIData = {
  totalProducts: products.length,
  totalValue: products.reduce((sum, p) => sum + p.price * p.stock, 0),
  lowStockAlerts: products.filter((p) => p.status === "low-stock" || p.status === "out-of-stock").length,
  ordersToday: 2,
  revenueThisMonth: 48750.32,
  revenueChange: 12.4,
  stockChange: -3.1,
};

export const chartData: ChartDataPoint[] = [
  { month: "Jan", revenue: 32100, orders: 187, stock: 1420 },
  { month: "Feb", revenue: 28400, orders: 165, stock: 1380 },
  { month: "Mar", revenue: 38900, orders: 223, stock: 1510 },
  { month: "Apr", revenue: 41200, orders: 248, stock: 1490 },
  { month: "May", revenue: 44500, orders: 271, stock: 1350 },
  { month: "Jun", revenue: 48750, orders: 298, stock: 1180 },
];
